import createStore from 'teaful';

export const { useStore } = createStore({
  step: 0,
  totalSteps: 9,
  time: '2 min',
  userData: {
    name: '',
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    state: '',
    flow: '',
    btn_src: '',
    ref: '',
    utm_source: '',
    utm_medium: '',
    utm_campaign: '',
    internal_ref: '',
    keyword: '',
    adgroup: '',
    internal_url: '',
    gaid: '',
    timezone: '',
    where_do_you_experience_pain: '',
    how_long: '',
    have_any_of_these: '',
    how_about_other_therapies: '',
    currently_treating_your_pain: '',
    how_familiar_are_you_with_the_topics_of_primary_pain: '',
    preferred_coach: '',
    payerDetails: '',
    partnerCode: '',
    affiliate_code: '',
  },
});
